name: Go

on:
  push:
    tags:        
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Lint
      run: make lint
    
    - name: Test
      run: make test
